### PR TITLE
Notify on payment failure

### LINKED ISSUE #43: SI: Notify Store Management When Checkout Payment Fails
As a store manager, I would like to be notified when an order payment fails, so that I may proactively contact the customer to resolve any payment issues.  

This feature would need to be carefully implemented, as it has the following challenges:  

- It would need to be configurable, to be turned on only in stores that wanted it. (Defaulted to being turned `Off` or `Disabled`)  
- There could easily be instances where a store would have too many notifications, and even too soon.  Many orders have failed transactions before the order is actually processed successfully.  
- Not all use cases will have customer information that would enable them to be contacted.  

It is proposed that this feature piggyback off of the abandoned cart feature, if implemented.  When the abandoned cart status is true for the order AND there is at least one failed transaction, then send out a summary notification of all failed orders for the day with links to the abandoned order in the administration area (and not individual failed order notifications).  

A scheduled job would be created to perform this activity, and turning the setting on/off would toggle the scheduled job to be enabled or disabled.  The scheduled job should be set to run once a day with a retry lapse of 30 minutes.  The e-mail template should follow the same pattern as the other e-mail templates in Hotcakes Commerce.  

An additional menu item should be added for `Failed` orders and only display the failed orders when selected.  This should follow the same pattern as the other "filtered" order views/pages.  This would allow store owners to proactively go look, without having to receive the e-mails.

### PR DESCRIPTION
**Pull request by alejoroman0605**
## Related to Issue
Fixes #43 

## Description

A functionality to notify the store admin about failed payments has been implemented. It is configurable and can be turned on/off from the store settings, with the following key features:

In the initial setup the functionality is disabled by default.
A daily email is sent that includes a summary of all orders with failed transactions, if they meet the criteria for an abandoned cart and transaction failures.
The functionality uses abandoned cart logic to identify relevant orders, with additional filters to detect possible order failures.
An order view has been added so that admins can check failed orders directly from the admin interface.
A Scheduled Job has been implemented, a daily process that sends notifications when enabled and attempts to resend it again after 30 minutes in case of failures.

## How Has This Been Tested?

I performed local testing on a site that did not have HCC installed, and the following checks were performed using Order Simulation with Transaction Failures:
Verification of configuration logic (enabling/disabling the feature).
Testing of notification generation based on failed transactions.
Confirming correct display of failed orders in the new view.
Validation that the scheduled job only runs when the functionality is enabled.

## Screenshots (if appropriate):
image
image
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: Website/DesktopModules/Hotcakes/Core/HotcakesController.cs [hunk 1]
```diff
@@ -152,6 +152,10 @@ public string UpgradeModule(string Version)
                     case "03.05.00":
                     case "03.06.00":
                         UpdateStoreSettings();
+                        break; 
+                    
+                    case "03.08.02":
```
Comment (WillStrohl) [inline Website/DesktopModules/Hotcakes/Core/HotcakesController.cs:157]: @alejoroman0605 Please update the version to `03.09.00`.

File: Website/DesktopModules/Hotcakes/Core/Admin/Reports/PaymentFailures/View.aspx [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+                <asp:Label ID="lblNoCartsMessage" resourcekey="NoPaymentFailuresFound" CssClass="hcInfoLabelLeft" Visible="false" runat="server" />
+            </div>
+        </div>
+
+        <asp:Panel ID="pnlReportsData" runat="server">
+            <asp:Repeater ID="rpCarts" runat="server">
+                <HeaderTemplate>
+                    <table class="hcGrid">
+                        <tr class="hcGridHeader">
+                            <th><%=Localization.GetString("OrderNumber") %></th>
```
Comment (WillStrohl) [inline Website/DesktopModules/Hotcakes/Core/Admin/Reports/PaymentFailures/View.aspx:60]: @alejoroman0605 Please make the order number link to the respective order.

File: Website/DesktopModules/Hotcakes/Providers/DataProviders/SqlDataProvider/02.00.00.SqlDataProvider [hunk 3]
```diff
@@ -137,6 +137,61 @@ BEGIN
...
 GO
 
+IF NOT EXISTS (SELECT 1 FROM {databaseOwner}[{objectQualifier}hcc_HtmlTemplates] WHERE [DisplayName] = N'Daily Online Order Payment Failure Report')
+BEGIN
+    INSERT INTO {databaseOwner}[{objectQualifier}hcc_HtmlTemplates] ([StoreId],[LastUpdatedUtc],[DisplayName],[FromEmail],[TemplateType])
+    VALUES (0, GETDATE(), N'Daily Online Order Payment Failure Report', N'[[Store.ContactEmail]]', 511)
+
+    INSERT INTO {databaseOwner}[{objectQualifier}hcc_HtmlTemplateTranslations] ([HtmlTemplateId],[Culture],[Subject],[Body],[RepeatingSection])
+    VALUES (@@IDENTITY, 'en-US', N'Daily Online Order Payment Failure Report', N'<html>
+    <head>
```
Comment (WillStrohl) [inline Website/DesktopModules/Hotcakes/Providers/DataProviders/SqlDataProvider/02.00.00.SqlDataProvider:147]: @alejoroman0605 Please remove the `<hr>` from the body.  Also, the orders should be an unordered list (`<ul>`).

**Review by WillStrohl — CHANGES_REQUESTED** [review]
Almost there! 💪🏽

File: Website/DesktopModules/Hotcakes/Core/Admin/Reports/PaymentFailures/View.aspx (hunk 2 above)
Comment (alejoroman0605) [reply Website/DesktopModules/Hotcakes/Core/Admin/Reports/PaymentFailures/View.aspx:60]: @WillStrohl I already added the link to the order number
image

File: Website/DesktopModules/Hotcakes/Core/HotcakesController.cs (hunk 1 above)
Comment (alejoroman0605) [reply Website/DesktopModules/Hotcakes/Core/HotcakesController.cs]: @WillStrohl I have already updated the version and also created a new provider for version 03.09.00.SqlDataProvider, because I realized that the creation of the "Daily Online Order Payment Failure Report" template was in a provider of a previous version.
